# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"J\n\x05Route\x12\x10\n\x08route_id\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05saddr\x18\x03 \x01(\t\x12\r\n\x05\x64\x61\x64\x64r\x18\x04 \x01(\t\"\x83\x02\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\x0c\x12#\n\x08metadata\x18\x02 \x01(\x0b\x32\x11.Message.Metadata\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a\xad\x01\n\x08Metadata\x12\x15\n\x05route\x18\x01 \x03(\x0b\x32\x06.Route\x12\x0b\n\x03src\x18\x02 \x01(\x0c\x12\x0b\n\x03\x64st\x18\x03 \x01(\x0c\x12\x13\n\x06gossip\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x12\x10\n\x03syn\x18\x05 \x01(\x0cH\x01\x88\x01\x01\x12\x10\n\x03\x61\x63k\x18\x06 \x01(\x0cH\x02\x88\x01\x01\x12\x12\n\x05topic\x18\x07 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_gossipB\x06\n\x04_synB\x06\n\x04_ackB\x08\n\x06_topicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROUTE']._serialized_start=17
  _globals['_ROUTE']._serialized_end=91
  _globals['_MESSAGE']._serialized_start=94
  _globals['_MESSAGE']._serialized_end=353
  _globals['_MESSAGE_METADATA']._serialized_start=180
  _globals['_MESSAGE_METADATA']._serialized_end=353
# @@protoc_insertion_point(module_scope)
